backend:
  name: github
  repo: dendyjoom/netlify
  auth_type: implicit
  app_id: 8e07cab818fa60a10783

media_folder: "assets/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Post" # Used in the UI
    folder: "_posts" # The path to the posts
    create: true # Allow users to create new posts
    slug: "{{slug}}" # Filename template
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "tags", label: "Tags", widget: "list" }
      - name: images
        label: "Images"
        label_singular: "Image"
        widget: list
        fields:
          - { label: "Alt", name: "alt", widget: "string" }
          - { label: "URL", name: "url", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }